### ISSUE TITLE
Understand background of project

### ISSUE THREAD

**Issue by MysterYusri** [SITINF2001P74/INF2001_P7-4#1]
### Description:

- This is where our Elicitation Phase starts.
- Applying the techniques learnt, we will gather all the information needed for the report.

### TODO:

- Read and understand project brief
- Based on the initial requirements provided, identify the Functional and Non-Functional requirements
- Identify questions to ask if the requirements is unclear during meet-up with client

**Comment by anonblader** [comment]
Done reading the project brief:

> Need Higher Level Requirements

**Comment by anonblader** [comment]
Had face2face client on 4th September 2023 @ 3:45PM.

**Comment by anonblader** [comment]
Completed.
