### ISSUE TITLE
[1.1.3] Intended Audience and Document Overview

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#13]
### Description:

- Describe the different types of reader that the document is intended for, such as developers, project managers, marketing staff, users, testers, and documentation writers (In your case it would probably be the “client” and the professor). 
- Describe what the rest of this document contains and how it is organized. 
- Suggest a sequence for reading the document, beginning with the overview sections and proceeding through the sections that are most pertinent to each reader type.

**Comment by Thura98** [comment]
Done. Please review.

**Comment by anonblader** [comment]
Reviewed with comments on the report.

Need further review. 

Thank you!

**Comment by Thura98** [comment]
Reviewing comments.

**Comment by anonblader** [comment]
Comments reviewed, and noted the changes.
