### ISSUE TITLE
Generating Requirements List

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#17]
### Description:
Populate a list of requirements based on what was gathered from initial client's interview.

### TODO: 

1) Specific Requirements:

- User Interface Requirements:
Describe the logical characteristics of each interface between the software product and the users. For this project, we only need to be concerned with the main thermostat (not the mobile app) and can use the graphic from the project description as the basis for your user interface.

- Functional Requirements:
Functional requirements capture the intended behavior of the system. This behavior may be expressed as services, tasks or functions the system is required to perform. This section is the direct continuation of section 2.2.2 where you have specified the general functional requirements. Here, you should list in detail the different product functions.

- Non-Functional Requirements:
Include any generic non-functional requirements. Please include a summary of the set of generic non-functional requirements.

- Performance Requirements:
If there are performance requirements for the product under various circumstances, state them here and explain their rationale, to help the developers understand the intent and make suitable design choices. Specify the timing relationships for real time systems. Make such requirements as specific as possible. You may need to state performance requirements for individual functional requirements or features.

- Safety and Security Requirements:
Specify those requirements that are concerned with possible loss, damage, or harm that could result from the use of the product. Define any safeguards or actions that must be taken, as well as actions that must be prevented. Refer to any external policies or regulations that state safety issues that affect the product’s design or use. Define any safety certifications that must be satisfied. Specify any requirements regarding security or privacy issues surrounding use of the product or protection of the data used or created by the product. Define any user identity authentication requirements.

### Success/Completion Criteria:

- Baseline requirements for User Interface have been laid out
- Requirements are clear and concise
- All team members have reviewed and agreeable to requirements

### Allocated Time (Start Date - End Date):

2 Weeks (4th September 2023 - 18th September 2023)

**Comment by MysterYusri** [comment]
Work done:
- The Performance Requirement have been identified.

Repo Status:
- Repo for report has been updated.

Completion Status:
- Pending team members' review.

**Comment by MysterYusri** [comment]
Work done:
- The Generic Non-Functional Requirement have been identified.

Repo Status:
- Repo for report has been updated.

Completion Status:
- Pending team members' review.

**Comment by MysterYusri** [comment]
Work done:
- The Safety and Security Requirement have been identified.

Repo Status:
- Repo for report has been updated.

Completion Status:
- Pending team members' review.

**Comment by anonblader** [comment]
Work done:
- User Interface Requirement (UIR) have been identified

Repo Status:
- Section 3.1 of Report for UIR have been updated

Completion Status:
- UIR (Completed)

Please review!

**Comment by anonblader** [comment]
@MysterYusri I have reviewed your updates.

**Comment by MysterYusri** [comment]
@anonblader UIR is good to go!

**Comment by anonblader** [comment]
I'll mark as completed.
