### ISSUE TITLE
[1.4.1] Software Estimation

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#20]
### Description:

Describe the resources required and overall time required for the project. Include your Gant Chart with WBS number and any other required charts like Burndown charts etc. here.

### TODO: 

- Gantt Chart with WBS number

### Success/Completion Criteria:

- Gantt Chart for M1 completed
- Reviewed by peer(s)

### Allocated Time (Start Date - End Date):

2 Weeks (4th September 2023 - 18th September 2023)

**Comment by anonblader** [comment]
Work Done:
- M1 Gantt Chart Completed

Repo Status:
- Added M1 Gantt Chart Screenshot to Section 4.2 of Project Management

Completion Status:
- Gantt Chart for M1 done (Completed)
- Pending Review by peers

**Comment by remo11201** [comment]
Reviewed

**Comment by remo11201** [comment]
Mark as completed
