### ISSUE TITLE
[1.4.2] Project Management

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#21]
### Description:

Include your Gant Chart with WBS number and any other required charts like Burndown charts etc. here.

### TODO: 

- Gantt Chart with WBS number
- Kanban Board Updates

### Success/Completion Criteria:

- Gantt Chart for M1 completed
- Kanban Board Updates For M1, M2 and M3 Completed.

### Allocated Time (Start Date - End Date):

2 Weeks (4th September 2023 - 18th September 2023)

**Comment by anonblader** [comment]
Work Done:
- Gantt Chart with WBS number updated
- Task owner assigned and reviewed
- Dates written and reviewed
- M1 Gantt Chart Completed
- Kanban Board For M1, M2 and M3 Completed

Repo Status:
- Added Appendix section for Gantt Chart in Report

Completion Status:
- Gantt Chart for M1 done (Completed)
- Kanban Board For M1, M2 and M3 done (Completed)

**Comment by 2102926** [comment]
Done and reviewed
