### ISSUE TITLE
[1.6] Appendix B - Data Dictionary

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#23]
### Description:

Data dictionary is used to track all the different variables, states and functional requirements that you described in your document. The purpose of the Data dictionary is to layout the definition of terms used in this document and align the readers to the authors perspectives. Make sure to include the complete list of all constants, state variables (and their possible states), inputs and outputs in a table. In the table, include the description of these items as well as all related operations and requirements.

_For Example:_

Term 1
List the definition of term 1 here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis purus ex, hendrerit sed mi consequat, dignissim lobortis velit.
Term 2
List the definition of term 2 here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis purus ex, hendrerit sed mi consequat, dignissim lobortis velit.
Term 3
List the definition of term 3 here.

### TODO: 

- List all the Technological Terms or Products Used for the Web Application

### Success/Completion Criteria:

- All technological terms have been listed
- Review by Peers

### Allocated Time (Start Date - End Date):

2 Days (4th September 2023 - 5th September 2023)

**Comment by anonblader** [comment]
Work Done:
- Identified the technological terms used in report
- Identified product terms used in report.

Repo Status:
- Updated Appendix B with list of Terms used in report.

Completion Status:
- List all Technological terms used in report done (Completed)
- Pending Review by peers

**Comment by anonblader** [comment]
Reviewed.

**Comment by 2102926** [comment]
Updated term. Pending Review

**Comment by anonblader** [comment]
Reviewed and task has met completion criteria.
