### ISSUE TITLE
[1.5.1] Appendix A - Use Case Descriptions 1-4

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#24]
### Description:
Based on the Use Cases identified in the Use Case Diagram, please write a detailed Use Case Description, and identify the Use Cases as UC-1 to UC-4.

### TODO: 
- Identify UC-1, UC-2, UC-3, UC-4
- Provide a Use Case Description for these Use Cases

### Success/Completion Criteria:
- Use Cases 1 to 4 have been identified
- Detailed description of Use Cases 1 to 4 have been laid out
- Reviewed by peer(s)

### Allocated Time (Start Date - End Date):

3 Days (11th September 2023 - 13th September 2023)

**Comment by anonblader** [comment]
Work Done:
- Use Cases 1 to 4 have been identified and numbered.
- Detailed description including the Success and Alternative Scenarios are written.

Repo Status:
- Appendix A for Use Case Description have been updated in the report.

Completion Status:
- UC-1 to UC-4 Identified (Completed)
- Description Provided (Completed)
- Pending Review from peers.

**Comment by 2102926** [comment]
Done and reviewed

**Comment by anonblader** [comment]
Reviewed and task has met completion criteria.
