### ISSUE TITLE
[2.3.3] Class Diagram

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#26]
### Description:
Describe and justify your design and concept rationale. Include your class diagram to have your complete entity, control and boundary classes. If your class diagram is too big, include only the interesting classes in this section, you can put your complete Class Diagram in Annex 6

### TODO: 
- Initial Class Diagram

### Success/Completion Criteria:
- Complete the Draft Class Diagram.
- Review by peer(s)

### Allocated Time (Start Date - End Date):

6 Days (19th October 2023 - 27th October 2023)

**Comment by 2102926** [comment]
Updated functions and class in ECB diagram, pending review

**Comment by anonblader** [comment]
Work done:
- Initial Class Diagram reviewed

Repo Status:
- M2 report not yet updated but updated on draw.io

Completion Status:
- Considered Complete, just need to place it in Annex 6 if Section 3 no space.
