### ISSUE TITLE
[2.3.2] Sequence Diagram

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#27]
### Description:
Include 2 sequence diagrams to explain the flow of your 2 prominent use cases. Remember to add them with your explanation.

### TODO: 
- Based on Use cases, do at least 5 Sequence Diagrams
- Choose 2 Prominent ones and place it into M2 Report

### Success/Completion Criteria:
- Confirm 2 Prominent Sequence Diagrams are in M2 Report
- Review by peer(s)

### Allocated Time (Start Date - End Date):

8 Days (16yh October 2023 - 25th October 2023)

### Priority

Medium

**Comment by 2102926** [comment]
Updated sequence diagram for use case 1 to 3 based on ecb diagram and use case descriptions, pending review

**Comment by anonblader** [comment]
Work Done:
- Reviewed Use cases 1 to 3
- Added Sequence Diagram for Use cases 4 and 5

Repo Status:
- Pending review and choosing of 2 prominent Sequence Diagram for M2 report

Completion Status:
- Pending review and placement in M2 report.

**Comment by 2102926** [comment]
Updated sequence diagram for use case 5 and 8, pending review

**Comment by MysterYusri** [comment]
Content have been finalised and reviewd.
