### ISSUE TITLE
[3.2.1] Black-Box Testing (Update Account)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#30]
### Description:
Blackbox testing on Critical Use Cases, starting off with update account.

### TODO: 
- Blackbox testing scenario

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (6th November 2023 - 10th November 2023)

### Priority

High

**Comment by 2102926** [comment]
Test Case on Update Account done, pending review.

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed
