### ISSUE TITLE
[3.2.2] Black-box testing (IT Admin's Create Accounts)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#31]
### Description:
Black box testing for IT Admin's Create accounts page.

### TODO: 
- Draft a scenario and use decision table for this testing

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (10th November 2023 - 17th November 2023)

### Priority

High

**Comment by Thura98** [comment]
Done, please review.

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed
