### ISSUE TITLE
[2.3.1] Component Diagram

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#33]
### Description:
You should use the component diagram to illustrate how the overall design of certain parts of the project comes together as one.

### TODO: 
- Initial Component Diagram

### Success/Completion Criteria:
- Initial Draft of Component Diagram Complete, ready for M2.
- Review by peer(s)

### Allocated Time (Start Date - End Date):

10 Days/Weeks (9th October 2023 - 20th October 2023)

### Priority:
Medium

**Comment by 2102926** [comment]
Updated component diagram, pending query from professor and review

**Comment by MysterYusri** [comment]
Component diagram have been updated. Prof reviewed and provided feedback that the diagram fits the requirement of the documentation.
