### ISSUE TITLE
[1.1] Introduction

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#34]
### Description:
Provide a brief introduction to your project, the intended purpose of the project, the impact of the project, and a brief overview of what the reader will find in this section. You can use the concise project description you have created to identify your nouns for your problem statement as a starting point and expand from there.

### TODO: 
- A summary of the entire report.

### Success/Completion Criteria:
- Paragraph contains:
_Brief intro to project
intended purpose of project
impact of project
brief overview of what reader will find_
- Review by peer(s)

### Allocated Time (Start Date - End Date):

2 Weeks (28th August 2023 - 1st September 2023)

### Priority:
High

**Comment by MysterYusri** [comment]
Work done:

- Written down a brief high-level product overview description explaining how the product is to be interact by the different actors
- Created a High-level System Architecture Diagram for Product Overview

Repo Status:

- Report has been updated with the work done contents

Completion Status:

- Team member to review

**Comment by anonblader** [comment]
Reviewed.

Thanks for the hard work!
