### ISSUE TITLE
[1.3.1] User Interface Requirements

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#36]
### Description:
Describe the logical characteristics of each interface between the software product and the users. For your project, you only need to be concerned with the main thermostat (not the mobile app) and can use the graphic from the project description as the basis for your user interface.

### TODO: 
Provide the graphic for the web application user interface and provide a basic description as to how users will interact (e.g., tough screen, menus, etc.)

### Success/Completion Criteria:
- UIR has been identified and laid out in report
- Review by peer(s)

### Allocated Time (Start Date - End Date):

4 Days (30th August 2023 - 4th September 2023)

### Priority:
High

**Comment by MysterYusri** [comment]
Work done:

- User Interface Requirement (UIR) have been identified.

Repo Status:

- Report has been updated to list down all the user interface requirements for the project.

Completion Status:

- Team member to review

**Comment by anonblader** [comment]
Reviewed.

Thanks for the hard work!
