### ISSUE TITLE
[1.3.2] Functional Requirements:

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#37]
### Description:
Functional requirements capture the intended behavior of the system. This behavior may be expressed as services, tasks or functions the system is required to perform. This section is the direct continuation of section 2.2 where you have specified the general functional requirements. Here, you should list in detail the different product functions.

### TODO:
- List functional requirements
- Use FR# (where # is the unique identifier for the requirement)
- Ensure that each FR are unique and its ONE requirement per sentence

### Success/Completion Criteria:
- At least 5 FRs based on requirements gathered
- Covers the baseline requirement according to Admin, Managers, Staff

### Allocated Time (Start Date - End Date):

4 Days (30th August 2023 - 4th September 2023)

### Priority:
High

**Comment by MysterYusri** [comment]
Work done:

- Functional Requirements have been identified.

Repo Status:

- Report has been updated to list down all the functional requirements for the different actors (IT admin, Manager and Staff)

Completion Status:

- Team member to review

**Comment by anonblader** [comment]
Reviewed.

Thanks for the hard work!
