### ISSUE TITLE
[1.3.3.1] Activity Diagram

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#38]
### Description:
This section displays the high-level activity diagram based on the workflow and processes of the Train Company. 

### TODO: 
- Activity Diagram for Manager
- Activity Diagram for Staff
- Activity Diagram for IT Admin

### Success/Completion Criteria:
- Processes have been linked to listed Actors
- Activity Diagrams for all are in the report

### Allocated Time (Start Date - End Date):

7 Days (5th September 2023 - 13th MMMM 2023)

### Priority:
High

**Comment by remo11201** [comment]
Done. Pls review

**Comment by anonblader** [comment]
Reviewed.
