### ISSUE TITLE
[1.3.4] Non-Functional Requirement

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#39]
### Description:
Include any generic non-functional requirements. Please include a summary of the set of generic non-functional requirements.

### TODO:
- List non-functional requirements
- Use NFR# (where # is the unique identifier for the requirement)
- Ensure that each NFR are unique and its ONE requirement per sentence

### Success/Completion Criteria:
- Covers the baseline for non-functional requirements.

### Allocated Time (Start Date - End Date):

4 Days (30th August 2023 - 4th September 2023)

### Priority:
High

**Comment by 2102926** [comment]
Work Done:

Short description of the section
Repo Status:

Section 3 updated with description of Non-functional Requirements section
Completion Status:

Description of Non-functional Requirements section (Completed)
Pending Peer Review

**Comment by anonblader** [comment]
Reviewed and met completion criteria.
