### ISSUE TITLE
[1.3.4.1] Performance Requirements

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#40]
### Description:
If there are performance requirements for the product under various circumstances, state them here and explain their rationale, to help the developers understand the intent and make suitable design choices. Specify the timing relationships for real time systems. Make such requirements as specific as possible. You may need to state performance requirements for individual functional requirements or features.

### TODO:
- List performance requirements
- Use PR# (where # is the unique identifier for the requirement)
- Ensure that each PR are unique and its ONE requirement per sentence

### Success/Completion Criteria:
- Covers the baseline for performance requirements.

### Allocated Time (Start Date - End Date):

4 Days (30th August 2023 - 4th September 2023)

### Priority:
High

**Comment by 2102926** [comment]
Work Done:

Short description of the section
Repo Status:

Section 3 updated with description of Performance Requirements section
Completion Status:

Description of Performance Requirements section (Completed)
Pending Peer Review

**Comment by anonblader** [comment]
Reviewed and met completion criteria.
