### ISSUE TITLE
[1.3.4.2] Safety And Security Requirements

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#41]
### Description:
Specify those requirements that are concerned with possible loss, damage, or harm that could result from the use of the product. Define any safeguards or actions that must be taken, as well as actions that must be prevented. Refer to any external policies or regulations that state safety issues that affect the product’s design or use. Define any safety certifications that must be satisfied. Specify any requirements regarding security or privacy issues surrounding use of the product or protection of the data used or created by the product. Define any user identity authentication requirements.

### TODO:
- List non-functional requirements
- Use SSR# (where # is the unique identifier for the requirement)
- Ensure that each SSR are unique and its ONE requirement per sentence

### Success/Completion Criteria:
- Covers the baseline for safety and security requirements.

### Allocated Time (Start Date - End Date):

4 Days (30th August 2023 - 4th September 2023)

### Priority:
High

**Comment by Wyxvern** [comment]
Work Done:
-  Safety and Security requirements have been identified

Repo Status:
-  Report has been updated to list down all Safety and Security requirements categorized into Safety and Security.

Completion Status:
-  Team member to review

**Comment by anonblader** [comment]
Reviewed.

Thanks for the hard work!
