### ISSUE TITLE
[1.3.5] Other Requirements

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#42]
### Description:
This section is Optional. Define any other requirements not covered elsewhere in the document. This might include database requirements, internationalization requirements, legal requirements, HBRA, PDPA, reuse objectives for the project, and so on. Add any new sections that are pertinent to the project.

### TODO:
- List additional requirements (that don't fall under other requirements)
- Use OR# (where # is the unique identifier for the requirement)
- Ensure that each OR are unique and its ONE requirement per sentence

### Success/Completion Criteria:
- Covers any additional requirements.

### Allocated Time (Start Date - End Date):

7 Days (5th September 2023 - 13th September 2023)

### Priority:
Low

**Comment by anonblader** [comment]
Work done:
- Added OR1

Repo Status:
- Section 3.5 of Report for Other Requirements have been updated.

Completion Status:
- Added 1 OR (Pending Review)

**Comment by 2102926** [comment]
Work done:

OR2 to 13
Repo Status:

Section 3.5 of Report for Other Requirements have been updated.
Completion Status:

Added OR2 to 13 (Pending Review)

**Comment by 2102926** [comment]
reviewed
