### ISSUE TITLE
[1.4.1] Software Estimation

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#44]
### Description:
Describe the resources required and overall time required for the project.

### TODO: 
- Provide rough calculations for software estimations.
- Use Excel spreadsheet and screenshot calculations.

### Success/Completion Criteria:
- Calculated Unadjusted weight for actors
- Derive Unadjusted weight and Unadjusted Use Case Points
- Calculate complexity
- Derived degree of influence

### Allocated Time (Start Date - End Date):

6 Days/Weeks (14th September 2023 - 21st September 2023)

### Priority:
High

**Comment by remo11201** [comment]
Done.Pls Review

**Comment by anonblader** [comment]
Reviewed.
