### ISSUE TITLE
[3.1.1] Wireframe Development (Skeletal)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#47]
### Description:
Develop a wireframe using Figma (or any other preferred tool) to create a prototype based on the project design.

### TODO: 
- Research on tools like Figma for prototyping

### Success/Completion Criteria:
- Chosen a wireframe tool or prototype tool
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (30th October 2023 - 3rd November 2023)

### Priority:
Low

**Comment by 2102926** [comment]
Wireframe for this action has been completed.

Pending review from team.

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed
