### ISSUE TITLE
[3.1.2.1] Manager's Landing Page

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#49]
### Description:
Using prototyping or wireframing tool, create the UI for the Manager.

### TODO: 
- Draft a UI prototype for the Manager's landing page.

### Success/Completion Criteria:
- Complete the UI design of the Manager's landing page based on project design and requirement.
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (30th October 2023 - 3rd November 2023)

### Priority:
Low

**Comment by Thura98** [comment]
Done, please review.

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed
