### ISSUE TITLE
[3.1.4.1] IT Admin's Landing Page

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#53]
### Description:
Using prototyping or wireframing tool, create the UI for the IT Admin UI based on project design.

### TODO: 
- Draft a UI prototype for the IT Admin UI.

### Success/Completion Criteria:
- Complete the UI design of the IT Admin UI based on project design and requirement.
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (30th October 2023 - 3rd November 2023)

### Priority:
Low

**Comment by 2102926** [comment]
Wireframe for this action has been completed.

Pending review from team.

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed
