### ISSUE TITLE
[2.1.1] Product Scope (Refined)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#54]
### Description:

Provide a short description of the changes in software scope (Compared to M1) 

### TO DO: 

- 1-2 paragraphs describing the change in scope of the product. 

### Success/Completion Criteria:

- Write any changes on the product scope (if any at all)
- Reviewed by Peer(s)

### Allocated Time (Start Date - End Date):

4 Days (25th September 2023 - 28th September 2023)

### Priority

Low

**Comment by MysterYusri** [comment]
Documentation have been updated and reviewed by the team. For the submission of documentation, the feedback provided have been addressed and recorded in the documentation.
