### ISSUE TITLE
[1.1.1] Product Scope

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#6]
### Description:

Provide a short description of the software scope, boundaries, and its purpose, including relevant benefits, objectives, and goals. 

### TO DO: 

- 1-2 paragraphs describing the scope of the product. 
- Make sure to describe the benefits associated with the product.

### Success/Completion Criteria:

- Product Scope has been identified and written
- Reviewed by Peer(s)

### Allocated Time (Start Date - End Date):

1 Week (11th September 2023 - 15th September 2023)

**Comment by Thura98** [comment]
Done. Please review.

**Comment by anonblader** [comment]
Reviewed.

**Comment by anonblader** [comment]
Mark as completed.
