### ISSUE TITLE
[3.2.1.3] Test Staff's Login

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#65]
### Description:
Blackbox testing on Critical Use Cases, starting off with login and landing page.

### TODO: 
- Blackbox testing scenario

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (6th November 2023 - 10th November 2023)

### Priority

High

**Comment by MysterYusri** [comment]
Blackbox done.

Pending team review.

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed
