### ISSUE TITLE
[1.1.2] Related Background Literature

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#7]
### Description:

Include research you have done about the domain that your project is in here. Any materials you read to help you with the project, and any competing methods/APIs/software.

### TODO: 

- Reference any related past research or works based on Train Services

### Success/Completion Criteria:

- Report is updated with past research with at least 1 paragraph
- Reviewed by peer(s)

### Allocated Time (Start Date - End Date):

1 Week (11th September 2023 - 15th September 2023)

**Comment by remo11201** [comment]
Done . Pls review

**Comment by anonblader** [comment]
Reviewed.

**Comment by anonblader** [comment]
Mark as completed.
