### ISSUE TITLE
[3.2.4.1] Test IT Admin Delete Account

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#73]
### Description:
Black box testing for IT Admin's Delete accounts page.

### TODO: 
- Draft a scenario and use decision table for this testing

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (10th November 2023 - 17th November 2023)

### Priority

High

**Comment by Wyxvern** [comment]
Work Done:
- Reviewed and tested the IT admin account deletion functionality.
- Identified and resolved any issues related to account deletion.
- Ensured that the deletion process followed the established flow.

Repo Status:
- Done the necessary screen capture and included it in the report

Completion Status:
- Reviewed and completed.

**Comment by remo11201** [comment]
Reviewed
