### ISSUE TITLE
[3.2.4.2] Test IT Admin Delete Account (Submit)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#74]
### Description:
Black box testing for IT Admin's Delete accounts page.

### TODO: 
- Draft a scenario and use decision table for this testing

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (10th November 2023 - 17th November 2023)

### Priority

High

**Comment by Wyxvern** [comment]
Work Done:
- Conducted a thorough review of the IT admin account deletion functionality.
- Identified and addressed any issues related to the account deletion process.
- Ensured that the deletion process adhered to established protocols and security measures.

Repo Status:
- Decision Table done in a separate document in a shared Google Drive folder.

Completion Status:
- Done and ready for review

**Comment by anonblader** [comment]
Reviewed All Tasks. This is completed.
