### ISSUE TITLE
[3.2.5] Black-box testing (Staff & Manager User Interface)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#75]
### Description:
Black box testing for Manager and Staff User Interfaces.

### TODO: 
- Draft a scenario and use decision table for this testing

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (10th November 2023 - 17th November 2023)

### Priority

High

**Comment by Wyxvern** [comment]
Work Done:
- Conducted a detailed analysis of the Staff and Manager User Interfaces to identify testing scenarios.
- Drafted testing scenarios covering various user interactions and edge cases.
- Created a comprehensive decision table to guide black-box testing, ensuring coverage of all possible input combinations.

Repo Status:
- Decision Table done in a separate document in a shared Google Drive folder.

Completion Status:
- Done and ready for review

**Comment by anonblader** [comment]
Reviewed All Tasks. This is completed.
