### ISSUE TITLE
[3.2.5.2] Test Manager's Job Assignment (Assigning)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#77]
### Description:
Black box testing for Manager's Job Assignment page.

### TODO: 
- Draft a scenario and use decision table for this testing

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (10th November 2023 - 17th November 2023)

### Priority

High

**Comment by Wyxvern** [comment]
Blackbox testing is done. Please review.

**Comment by anonblader** [comment]
Reviewed All Tasks. This is completed.
