### ISSUE TITLE
[3.2.5.4] Test Staff's Job Rejection

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#79]
### Description:
Black box testing for Staff's Job Rejection Use case.

### TODO: 
- Draft a scenario and use decision table for this testing

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (10th November 2023 - 17th November 2023)

### Priority

High

**Comment by remo11201** [comment]
Done.Pls review

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed.
