### ISSUE TITLE
[1.1.4] References and Acknowledgements

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#8]
### Description:

List any other documents or Web addresses to which this document refers. These may include user interface style guides, contracts, standards, system requirements specifications, use case documents, or a vision and scope document.

### TODO: 

- Cite all the references done for Section 1 of the report.

### Success/Completion Criteria:

- Complete Citation of References
- Reviewed by Peers

### Allocated Time (Start Date - End Date):

1 Week (11th September 2023 - 15th September 2023)

**Comment by remo11201** [comment]
Done. Pls Review

**Comment by anonblader** [comment]
Reviewed.

**Comment by anonblader** [comment]
Mark as completed.
