### ISSUE TITLE
[3.2.6] Whitebox testing (Control Flow Test)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#82]
### Description:
Whitebox testing for a Manager's Use case.

### TODO: 
- Draft a scenario and use suitable method (Control Graph, etc..)

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

9 Days (14th November 2023 - 24th November 2023)

### Priority

High

**Comment by MysterYusri** [comment]
Whitebox testing done and documented.

Pending team review.

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed.
