### ISSUE TITLE
[3.2.6.1] Pseudocode (Manager's Use Case)

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#83]
### Description:
Draft a pseudocode for all use cases, we will pick suitable 4 and filter out 2 to use.

### TODO: 
- Manager's Use cases for pseudocode.

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

2 Days (2nd November 2023 - 3rd November 2023)

### Priority

High

**Comment by remo11201** [comment]
Done. Pls review

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed.
