### ISSUE TITLE
[3.2.6.4] Whitebox testing Test Cases

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#86]
### Description:
Any other test cases to use for additional methods.

### TODO: 
- Test cases.

### Success/Completion Criteria:
- Review by peer(s)

### Allocated Time (Start Date - End Date):

9 Days (14th November 2023 - 24th November 2023)

### Priority

High

**Comment by 2102926** [comment]
Test Case on Assigning Job to staff done

**Comment by Wyxvern** [comment]
Reviewed and Marked as Completed.
