### ISSUE TITLE
[1.2.1] Product Overview

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#9]
### Description:

Describe the context and origin of the product being specified in this document. For example, state whether this product is a follow-on member of a product family, a replacement for certain existing systems, or a new, self-contained product. If the document defines a component of a larger system, relate the requirements of the larger system to the functionality of this software and identify interfaces between the two. In this part, make sure to include a simple diagram that shows the major components of the overall system, subsystem interconnections, and external interface. In this section it is crucial that you will be creative and provide as much information as possible.

### TODO: 

- Provide at least one paragraph describing product perspective. 
- Provide your System’s Architecture diagram to illustrate how your product interacts with the environment and in what context it is being used.  
- This is not a formal diagram, but rather something that is used to illustrate the product at a high level.

### Success/Completion Criteria:
- At least 1 paragraph under the section
- Have a high-level System Architecture Diagram
- Review by peer(s)

### Allocated Time (Start Date - End Date):

2 Weeks (4th September 2023 - 21st September 2023)

**Comment by anonblader** [comment]
Work Done:
- 2 Paragraphs of Product Overview

Repo Status:
- Report section 2.1 for Product Overview updated.

Completion Status:
- Pending System's Architecture Diagram
- Pending Peer(s) review.

**Comment by remo11201** [comment]
Reviewed
