### ISSUE TITLE
[3.1.3.5] Staff's Job Preference Page

### ISSUE THREAD

**Issue by anonblader** [SITINF2001P74/INF2001_P7-4#95]
### Description:
Using prototyping or wireframing tool, create the UI for the Staff.

### TODO: 
- Draft a UI prototype for the Staff's job preference page.

### Success/Completion Criteria:
- Complete the UI design of the Staff page based on project design and requirement.
- Review by peer(s)

### Allocated Time (Start Date - End Date):

5 Days (30th October 2023 - 3rd November 2023)

### Priority:
Low

**Comment by Wyxvern** [comment]
Work Done:
- Conducted a thorough analysis of the requirements for the Staff's Job Preference Page.
- Designed a user interface that aligns with the project's aesthetic and functional goals.
- Incorporated elements such as form fields, buttons, and visual cues for an intuitive user experience.

Repo Status:
- Ensured that design assets, such as mockups, were organized in the Figma repository.

Completion Status:
- The UI design is complete and ready for review.

**Comment by anonblader** [comment]
Reviewed All Tasks. This is completed.
